language: minimal

script: mkdir _site && make package

before_deploy:
    - git config --local user.name "Kirill Sulim"
    - git config --local user.email "kirillsulim@gmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG

deploy:
    provider: releases
    api_key: ${GITHUB_OAUTH_TOKEN}
    file: "su0.io.tar.gz"
    skip_cleanup: true
